site_name: ${{values.app_name}}
site_description: Go Snake-game app — ${{values.app_name}}
repo_url: https://github.com/octal-engine/${{values.app_name}}
edit_uri: edit/main/docs/

plugins:
  - techdocs-core

nav:
  - Getting Started: index.md
